# Change these first
owner: Cloudwhiz-Digitech-Global-Ventures # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

# CloudWhiz Sites List
sites:
  - name: CloudWhiz.co.in
    url: https://www.cloudwhiz.co.in
  - name: CloudWhiz.org.in
    url: https://www.cloudwhiz.org.in
  - name: Clowud.com
    url: https://www.clowud.com
  - name: Clowud.in
    url: https://www.clowud.in
  - name: Clowud.ae
    url: https://www.clowud.ae
  - name: Clowud.us
    url: https://www.clowud.us
  - name: Clowud.shop
    url: https://www.clowud.shop
  - name: Clowud Support
    url: https://support.clowud.com
  - name: CloudWhiz Mail
    url: https://mail.cloudwhiz.co.in
  - name: CloudWhiz.in
    url: https://www.cloudwhiz.in
  - name: CloudWhiz.org
    url: https://www.cloudwhiz.org
  - name: CloudWhiz.ae
    url: https://www.cloudwhiz.ae
  - name: CloudWhiz IPv6 test
    url: cloudwhiz.co.in
    port: 443
    check: "tcp-ping"
    ipv6: true
  - name: Clowud IPv6 test
    url: host23.clowud.com
    port: 443
    check: "tcp-ping"
    ipv6: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.cloudwhiz.co.in
  # baseUrl: /your-repo-name
  logoUrl: https://d1xuv411iyp43l.cloudfront.net/HTSzFA0QghGmuGqT/logos/cloudwhiz-logo.svg
  name: CloudWhiz
  introTitle: "**CloudWhiz** Uptime Status"
  introMessage:
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
# Run 5
